// /controllers/ strings, English (served at /controllers/).
// Shape must match zh.mjs key for key — tools/build-controllers.mjs refuses to build otherwise.
// Strings may contain inline HTML (authored, trusted). Device data, code, signal names and URLs
// come from packages/midi/profiles/*.json and tools/controllers/page.mjs, never from here.
// {n}, {tool}, {port} … are filled in by the page.

export default {
  lang: 'en',
  htmlLang: 'en',

  meta: {
    title: 'MIDI controllers, modeled · open-audiovisual',
    description: 'MIDI controllers described as data: every knob, pad and key with its exact MIDI message and the document it came from. Play them on screen, plug the real one in, embed one in any page with one line. Arturia, AKAI, Novation, KORG and generic layouts.',
    ogDescription: 'Every knob, pad and key with its exact MIDI message and its source. Play it on screen, plug the real one in, embed it with one line.',
    ldName: 'open-audiovisual MIDI controller profiles',
    ldDescription: 'Machine-readable MIDI implementation charts for hardware controllers: faceplate layout, every control\'s MIDI message, LED feedback, port-name matching and cited sources, as JSON (MIT).',
    ldList: 'MIDI controllers in the open-audiovisual library',
  },

  hero: {
    eyebrow: '01 · Play',
    title: 'MIDI controllers, modeled.',
    lede: 'A library of MIDI controllers written as data: every knob, pad and key with the exact MIDI message it sends and the document that number came from. Play them here, plug the real one in and watch it move, or put one in your own page with a single line.',
    why: 'Every music tool makes you map your controller again. Here a controller is modeled once, with sources, for everyone to use.',
    stats: { devices: 'devices', generic: 'generic layouts', controls: 'controls on the devices', sources: 'sources cited' },
    unverified: '{n} of those controls are marked <em>unverified</em>: the number is our best reading, and learn mode rebinds it in one move.',
    switchLabel: 'Choose a controller',
    devices: 'Devices',
    generic: 'Generic',
    connect: 'Connect your controller',
    asking: 'Asking for MIDI…',
    connected: 'Connected: {port}',
    waiting: 'Listening. Plug in a known device and it appears here.',
    noMidi: 'This browser has no Web MIDI (Safari, iPad). Play on screen: every event still fires.',
    denied: 'MIDI permission was blocked. Allow it in the address bar and try again.',
    readoutIdle: 'Touch a control: its signal and MIDI message appear here.',
    readoutLabel: 'Last message',
    hint: 'Drag knobs and faders · tap pads and keys · Tab and arrow keys work too',
    noscript: 'This is a live, playable controller. Turn on JavaScript to play it. Every device\'s MIDI map is in the spec sheets below.',
    specLink: 'Spec sheet',
    fullLink: 'Full screen',
    controlsN: '{n} controls',
  },

  catalog: {
    eyebrow: '02 · Catalog',
    title: 'Every controller in the library',
    lede: 'The faceplates on these cards are the component itself, live: drag them. The badges say where each profile\'s numbers come from.',
    devices: 'Devices',
    generic: 'Generic layouts',
    genericNote: 'For a controller that is not in the library yet: pick the layout closest to it, press Learn, and move your controls in order.',
    filterLabel: 'Show controllers with',
    filters: { all: 'All', pad: 'Pads', keys: 'Keys', knob: 'Knobs', fader: 'Faders', encoder: 'Encoders', led: 'LED feedback' },
    shown: '{n} shown',
    badges: { maker: 'Manufacturer docs', community: 'Community notes', tool: 'Artist\'s {tool} tool', generic: 'Generic layout', unverified: '{n} unverified', led: 'LED feedback' },
    links: { play: 'Play', full: 'Full screen', json: 'JSON', embed: 'Embed', spec: 'Spec sheet' },
    faceLabel: 'Faceplate of {name}',
    tapToPlay: 'Tap Play to try it on the big one above.',
  },

  types: {
    knob: ['{n} knob', '{n} knobs'],
    encoder: ['{n} encoder', '{n} encoders'],
    fader: ['{n} fader', '{n} faders'],
    pad: ['{n} pad', '{n} pads'],
    button: ['{n} button', '{n} buttons'],
    keys: ['{n} key', '{n} keys'],
    wheel: ['{n} wheel', '{n} wheels'],
    strip: ['{n} touch strip', '{n} touch strips'],
  },
  typeNames: { knob: 'knob', encoder: 'encoder', fader: 'fader', pad: 'pad', button: 'button', keys: 'keys', wheel: 'wheel', strip: 'touch strip' },

  specs: {
    eyebrow: '03 · Spec sheets',
    title: 'The full MIDI map of each one',
    lede: 'Generated from the JSON files at build time, so they cannot drift from what the component plays. Numbers and signal names are the same in every language; notes and sources stay in the language they were written in.',
    cols: { control: 'Control', type: 'Type', message: 'Message', ch: 'Ch', number: 'Number', signal: 'Signal', led: 'LED feedback', verified: 'Verified' },
    caption: 'MIDI implementation of {name}',
    msg: { cc: 'CC', note: 'Note', pitchbend: 'Pitch bend', chanat: 'Channel pressure', program: 'Program change' },
    relative: 'relative ({mode})',
    absolute: 'absolute',
    momentary: 'momentary',
    toggle: 'toggle',
    velocity: 'velocity',
    polyAt: '+ poly aftertouch',
    chanAt: '+ channel pressure',
    spring: 'springs to centre',
    bendRange: '0–16383 · centre 8192',
    keysRange: '{from}–{to} ({a}–{b})',
    led: { note: 'note', cc: 'CC', on: 'on', off: 'off', velocity: 'velocity' },
    yes: 'yes',
    unverified: 'unverified',
    ledNone: '—',
    sources: 'Sources',
    sourceKinds: { maker: 'manufacturer', community: 'community', tool: 'artist\'s tool', convention: 'convention' },
    origin: 'Where this profile comes from',
    notes: 'Notes',
    controlNotes: 'Notes on single controls',
    ports: 'Port names it recognises',
    match: { ports: 'matches', prefer: 'prefers', avoid: 'avoids' },
    noMatch: 'Generic layouts never match a port by themselves: assign one by hand, then learn.',
    signals: 'Signals',
    signalsText: 'Every control publishes <code>midi/{short}/&lt;control&gt;</code> (0..1), plus <code>/raw</code>; pads add <code>/hit</code>, encoders <code>/delta</code>, keys <code>/on</code> <code>/off</code> and <code>n&lt;note&gt;</code>; the last control touched is <code>midi/{short}/last</code>.',
    raw: 'Raw JSON',
    open: 'Open spec sheet',
    toCard: 'Its card',
  },

  embed: {
    eyebrow: '04 · Embed it',
    title: 'Put one in your page',
    lede: 'One line of HTML, an iframe, or JavaScript. Choose a device and options: the preview and every snippet below follow.',
    form: {
      device: 'Device', layout: 'Layout', show: 'Show', hardware: 'Hardware', midiOut: 'MIDI out', theme: 'Theme',
      layouts: { auto: 'Auto', face: 'Faceplate', stack: 'Stacked' },
      picker: 'device picker', readout: 'last message', learn: 'learn button',
      hw: { off: 'Off', ask: 'Button (asks on click)', on: 'Connect on load' },
      out: { off: 'Off', ask: 'Visitor picks a port', IAC: 'IAC bus (macOS)', loopMIDI: 'loopMIDI (Windows)' },
      themes: { dark: 'Dark', light: 'Light' },
    },
    preview: 'Live preview',
    events: 'The last event, as your code receives it',
    eventsIdle: 'Play the preview: its <code>control</code> event appears here.',
    snips: [
      { title: 'One line, any page', text: 'No import map, no build step. Shadow DOM keeps your page\'s CSS out and the controller\'s CSS in.' },
      { title: 'An iframe', text: 'For places that only take an iframe. Every event arrives as a <code>postMessage</code>; you can send <code>set</code> and <code>ingest</code> back.' },
      { title: 'JavaScript, any framework', text: '<code>createController()</code> is the element without the element: React, Vue, Svelte or plain. It works headless, with no faceplate at all.' },
      { title: 'Listen to it', text: 'Events bubble and cross the shadow root. Each payload is plain JSON: the control, its value, its signal name, the MIDI message and the bytes.' },
      { title: 'Play your DAW with it', text: 'What you play on screen leaves as real MIDI, into Ableton Live, TouchDesigner, Resolume or any software that takes a MIDI input.' },
    ],
    dawTitle: 'MIDI out to Ableton, TouchDesigner, Resolume',
    mac: [
      'macOS: open <b>Audio MIDI Setup</b> → Window → Show MIDI Studio, double-click <b>IAC Driver</b>, tick “Device is online”.',
      'Windows: install <a href="https://www.tobias-erichsen.de/software/loopmidi.html">loopMIDI</a> and add a port.',
      'Ableton Live: Settings → Link, Tempo &amp; MIDI → turn on Track and Remote for the IAC or loopMIDI input. TouchDesigner: a MIDI In CHOP on that device. Resolume: Preferences → MIDI.',
    ],
    browsers: 'Web MIDI works in Chrome and Edge, and in Firefox after it asks you to allow the site. Safari and iPad have none: the controller still plays and fires every event, and MIDI out reports that it is unavailable.',
    loop: 'No feedback loops: the engine never listens to IAC inputs, the element mutes any input with the same name as its output (the loopMIDI echo), and moves from your real hardware are not forwarded, because your software already hears the device.',
    telemetry: 'Usage stats: each embed sends one anonymous hit per page load (which kind, which controller, the page’s origin; no cookies, nothing you play). <code>telemetry="off"</code> turns it off. <a href="{href}">What exactly is sent</a>.',
    protocolTitle: 'iframe messages',
    protocolText: 'The iframe posts every event to its parent and accepts a few commands back. Add <code>&amp;frame=name</code> to tell several iframes apart, and <code>&amp;origin=https://your.site</code> to talk to your page only.',
    apiTitle: 'The element, in one table',
    apiCols: { name: 'Name', kind: 'Kind', what: 'What it does' },
    api: [
      { name: 'profile', kind: 'attribute', what: 'which device: an id, a short name, or a URL to a profile JSON' },
      { name: 'layout', kind: 'attribute', what: 'auto, face (as it looks) or stack (re-gridded for a tall box)' },
      { name: 'hardware', kind: 'attribute', what: 'follow the real device: on, ask (a button), or a port name' },
      { name: 'midi-out', kind: 'attribute', what: 'send what is played to an output: a port name, /regex/, or ask' },
      { name: 'channel', kind: 'attribute', what: '1–16: move every control to the channel your unit is set to' },
      { name: 'picker · readout · learn · follow', kind: 'attribute', what: 'device picker, last-message line, learn button, switch to the device you plug in' },
      { name: 'control', kind: 'event', what: 'any control moved: id, type, value, raw, signal, message, bytes, source' },
      { name: 'noteon · noteoff', kind: 'event', what: 'pads, keys and note buttons, with note and velocity' },
      { name: 'connect · disconnect · status', kind: 'event', what: 'the hardware port came or went; the state of hardware and MIDI out' },
      { name: 'set(id, value) · get(id) · values() · reset()', kind: 'method', what: 'move a control like a hand would, read it, read all, bring all home' },
      { name: 'ingest(bytes) · send(bytes)', kind: 'method', what: 'MIDI in from anywhere (the faceplate follows) · raw bytes to the output port' },
      { name: 'on(name, fn)', kind: 'method', what: 'subscribe, returns an unsubscribe function' },
    ],
    readme: 'Everything, with every field of every payload: the package README',
  },

  model: {
    eyebrow: '05 · Model yours',
    title: 'Add your controller',
    lede: 'A profile is one JSON file. If the manual has a MIDI implementation chart, the profile can be exact; if it does not, say so in the file.',
    steps: [
      { head: 'Start from the closest file', text: 'Copy a device that looks like yours, or a generic layout. The faceplate is sections on a grid in face units, so the screen version looks like the desk.' },
      { head: 'Write down what each control sends', text: 'Type, message (<code>cc</code>, <code>note</code>, <code>pitchbend</code>), channel, number. Encoders name their relative mode; buttons say momentary or toggle; LEDs say what lights them.' },
      { head: 'Cite every number', text: 'Each source has a title, a link and what it confirmed. A number nobody has checked gets <code>"verified": false</code> and a note.' },
      { head: 'Validate', text: '<code>validateProfile()</code> returns every problem in words, or an empty list. The test suite runs it on every shipped profile.' },
      { head: 'Try it before you send it', text: '<code>&lt;oav-controller profile="./my-pads.json"&gt;</code> loads a profile from a URL, so you can play your file on your own page first.' },
      { head: 'Open a pull request', text: 'Put the file in <code>packages/midi/profiles/</code> and add it to <code>profiles/index.js</code>. Tell us which unit and firmware you checked it on.' },
    ],
    typesTitle: 'Control types',
    typesCols: { type: 'Type', sends: 'Sends', signal: 'Signal value' },
    types: [
      { type: 'knob · fader', sends: 'CC, absolute 0–127', signal: '0..1' },
      { type: 'encoder', sends: 'CC, relative (offset64, offset16, twos, signbit)', signal: 'position 0..1, plus /delta steps' },
      { type: 'pad', sends: 'note with velocity (or CC); optional aftertouch', signal: 'velocity while held, 0 on release, plus /hit' },
      { type: 'button', sends: 'note or CC; momentary or toggle', signal: '0 or 1' },
      { type: 'keys', sends: 'a note range', signal: '/on and /off pulses, n&lt;note&gt; while held' },
      { type: 'wheel · strip', sends: 'CC or pitch bend; may spring back', signal: '0..1, or −1..1 when bipolar' },
    ],
    schemaTitle: 'A profile, in short',
    validateTitle: 'Check it',
    learnTitle: 'No manual? Learn it',
    learnText: 'Choose a generic layout, press Learn, and move your controls in order: the layout fills itself with your device\'s messages. <code>exportMapping()</code> gives you the result as JSON, the start of a real profile.',
    links: { repo: 'The repository', readme: 'packages/midi/README.md', folder: 'All profile files', issue: 'Ask for a controller' },
  },
};
