// /zh/controllers/ 字串，繁體中文（台灣）。
// 結構必須和 en.mjs 一模一樣（每個 key、每個陣列長度），tools/build-controllers.mjs 會檢查。
// 字串可以含 inline HTML。裝置資料、程式碼、訊號名稱與網址來自 packages/midi/profiles/*.json
// 和 tools/controllers/page.mjs，兩種語言共用。{n}、{tool}、{port} 由頁面填入。

export default {
  lang: 'zh',
  htmlLang: 'zh-Hant-TW',

  meta: {
    title: 'MIDI 控制器圖鑑｜open-audiovisual',
    description: '每一顆旋鈕、打擊墊、琴鍵送出什麼 MIDI 訊息，數字出自哪一份手冊，這裡都查好了。在網頁上直接彈，接上手邊的控制器畫面會跟著動，一行程式碼就能放進自己的網頁。收錄 Arturia、AKAI、Novation、KORG、Behringer 與通用版面。',
    ogDescription: '每一顆旋鈕送出什麼 MIDI 訊息、數字出自哪份手冊，都查好了。網頁上直接彈，接上控制器會跟著動，一行程式碼放進你的網頁。',
    ldName: 'open-audiovisual MIDI 控制器設定檔',
    ldDescription: '機器可讀的硬體 MIDI 控制器實作表：面板配置、每個控制項的 MIDI 訊息、LED 回饋、埠名稱比對與引用出處，JSON 格式（MIT 授權）。',
    ldList: 'open-audiovisual 資料庫裡的 MIDI 控制器',
  },

  hero: {
    eyebrow: '01 · 彈奏',
    title: 'MIDI 控制器圖鑑',
    lede: '每一顆旋鈕、打擊墊、琴鍵按下去送出什麼 MIDI 訊息，這個數字出自哪一份手冊，這裡都查好寫清楚了。用滑鼠或手指直接彈，接上你手邊的控制器，畫面會跟著你的手動，也可以用一行程式碼放進自己的網頁。',
    why: '以前每換一套軟體，就要把手上的控制器重新對一次，CC 幾號、哪個頻道，每個人都在翻同一本手冊。這裡把每一台查一次、建好模型、附上出處，之後大家直接拿去用。',
    stats: { devices: '台裝置', generic: '種通用版面', controls: '個裝置上的控制項', sources: '份引用出處' },
    unverified: '其中 {n} 個控制項標了<em>未確認</em>，還沒找到文件證實，數字先照目前的判讀。對不上的話，按「學習」再動一下那顆鈕，就會重新對應。',
    switchLabel: '選一台控制器',
    devices: '裝置',
    generic: '通用',
    connect: '接上你的控制器',
    asking: '正在請求 MIDI…',
    connected: '已連接：{port}',
    waiting: '等你接上控制器。這裡有收錄的機型，一接上就會自動切過去。',
    noMidi: '這個瀏覽器沒有 Web MIDI（Safari、iPad），接不了實體控制器，但在螢幕上彈照樣會送出每個事件。',
    denied: 'MIDI 權限被擋下了。在網址列允許之後再試一次。',
    readoutIdle: '轉一顆旋鈕試試，它的訊號和 MIDI 訊息會出現在這裡。',
    readoutLabel: '最後一則訊息',
    hint: '拖曳旋鈕和推桿 · 點打擊墊和琴鍵 · 也可以用 Tab 和方向鍵',
    noscript: '這裡是一台可以彈的控制器，打開 JavaScript 才能彈。每一台完整的 MIDI 對照，都在下面的規格表裡。',
    specLink: '規格表',
    fullLink: '全螢幕',
    controlsN: '{n} 個控制項',
  },

  catalog: {
    eyebrow: '02 · 目錄',
    title: '目前收錄的控制器',
    lede: '卡片上的面板就是元件本身，可以直接拖、直接按。底下的標籤寫著這一台的數字是從哪裡查來的。',
    devices: '裝置',
    generic: '通用版面',
    genericNote: '找不到你那一台的話，先挑一個最接近的版面，按「學習」，再照順序把你手上的旋鈕和推桿各動一次。',
    filterLabel: '篩選：有這些控制的',
    filters: { all: '全部', pad: '打擊墊', keys: '琴鍵', knob: '旋鈕', fader: '推桿', encoder: '無段旋鈕', led: 'LED 回饋' },
    shown: '顯示 {n} 台',
    badges: { maker: '原廠文件', community: '社群整理', tool: '作者的 {tool} 工具', generic: '通用版面', unverified: '{n} 個未確認', led: 'LED 回饋' },
    links: { play: '彈奏', full: '全螢幕', json: 'JSON', embed: '嵌入', spec: '規格表' },
    faceLabel: '{name} 的面板',
    tapToPlay: '按「彈奏」，換到上面的大面板去彈。',
  },

  types: {
    knob: ['{n} 顆旋鈕', '{n} 顆旋鈕'],
    encoder: ['{n} 顆無段旋鈕', '{n} 顆無段旋鈕'],
    fader: ['{n} 支推桿', '{n} 支推桿'],
    pad: ['{n} 個打擊墊', '{n} 個打擊墊'],
    button: ['{n} 顆按鈕', '{n} 顆按鈕'],
    keys: ['{n} 個琴鍵', '{n} 個琴鍵'],
    wheel: ['{n} 個滾輪', '{n} 個滾輪'],
    strip: ['{n} 條觸控條', '{n} 條觸控條'],
  },
  typeNames: { knob: '旋鈕', encoder: '無段旋鈕', fader: '推桿', pad: '打擊墊', button: '按鈕', keys: '琴鍵', wheel: '滾輪', strip: '觸控條' },

  specs: {
    eyebrow: '03 · 規格表',
    title: '每一台的完整 MIDI 對照表',
    lede: '這些表在建置時直接從 JSON 檔產生，跟元件實際送出的訊息一定對得上。數字和訊號名稱中英文版都一樣，說明和出處保留原文。',
    cols: { control: '控制項', type: '類型', message: '訊息', ch: '頻道', number: '編號', signal: '訊號', led: 'LED 回饋', verified: '已確認' },
    caption: '{name} 的 MIDI 實作表',
    msg: { cc: 'CC', note: '音符', pitchbend: '彎音', chanat: '通道觸後', program: '音色切換' },
    relative: '相對值（{mode}）',
    absolute: '絕對值',
    momentary: '按住',
    toggle: '切換',
    velocity: '力度',
    polyAt: '＋複音觸後',
    chanAt: '＋通道觸後',
    spring: '放開回中央',
    bendRange: '0–16383 · 中央 8192',
    keysRange: '{from}–{to}（{a}–{b}）',
    led: { note: '音符', cc: 'CC', on: '亮', off: '暗', velocity: '依力度' },
    yes: '是',
    unverified: '未確認',
    ledNone: '—',
    sources: '出處',
    sourceKinds: { maker: '原廠', community: '社群', tool: '作者的工具', convention: '慣例' },
    origin: '這個設定檔從哪裡來',
    notes: '說明',
    controlNotes: '個別控制項的說明',
    ports: '認得的埠名稱',
    match: { ports: '比對', prefer: '優先', avoid: '避開' },
    noMatch: '通用版面不會自己比對埠：手動指定一個埠，再用學習模式。',
    signals: '訊號',
    signalsText: '每個控制項都會發出 <code>midi/{short}/&lt;控制項&gt;</code>（0..1）和 <code>/raw</code>。打擊墊多一個 <code>/hit</code>，無段旋鈕多 <code>/delta</code>，琴鍵有 <code>/on</code>、<code>/off</code> 和 <code>n&lt;音高&gt;</code>。最後動到的那個控制項是 <code>midi/{short}/last</code>。',
    raw: '原始 JSON',
    open: '打開規格表',
    toCard: '回到卡片',
  },

  embed: {
    eyebrow: '04 · 嵌入',
    title: '放進你的網頁',
    lede: '一行 HTML、一個 iframe，或一段 JavaScript 都可以。先選機型和選項，預覽和下面每一段程式碼會跟著換。',
    form: {
      device: '裝置', layout: '版面', show: '顯示', hardware: '硬體', midiOut: 'MIDI 輸出', theme: '配色',
      layouts: { auto: '自動', face: '面板', stack: '堆疊' },
      picker: '裝置選單', readout: '最後一則訊息', learn: '學習按鈕',
      hw: { off: '關', ask: '按鈕（點了才請求）', on: '載入就連接' },
      out: { off: '關', ask: '讓訪客選埠', IAC: 'IAC 匯流排（macOS）', loopMIDI: 'loopMIDI（Windows）' },
      themes: { dark: '深色', light: '淺色' },
    },
    preview: '即時預覽',
    events: '最後一個事件，你的程式收到的樣子',
    eventsIdle: '彈一下預覽，它的 <code>control</code> 事件會出現在這裡。',
    snips: [
      { title: '一行，任何網頁', text: '不用 import map，不用建置。Shadow DOM 讓你網頁的 CSS 進不來，控制器的 CSS 也出不去。' },
      { title: 'iframe', text: '給只能放 iframe 的地方。每個事件都會用 <code>postMessage</code> 傳出來，你也可以把 <code>set</code>、<code>ingest</code> 傳回去。' },
      { title: 'JavaScript，任何框架', text: '<code>createController()</code> 就是不帶元素的元素：React、Vue、Svelte 或純 JS 都能用。不畫面板也能跑。' },
      { title: '聽它', text: '事件會冒泡，也會穿過 shadow root。每個事件內容都是單純的 JSON：控制項、數值、訊號名稱、MIDI 訊息和位元組。' },
      { title: '拿它彈你的 DAW', text: '在螢幕上彈的，會變成真的 MIDI 送出去，進到 Ableton Live、TouchDesigner、Resolume，或任何收 MIDI 輸入的軟體。' },
    ],
    dawTitle: 'MIDI 輸出到 Ableton、TouchDesigner、Resolume',
    mac: [
      'macOS：打開<b>音訊 MIDI 設定</b> → 視窗 → 顯示 MIDI 工作室，雙擊 <b>IAC 驅動程式</b>，勾選「裝置已上線」。',
      'Windows：安裝 <a href="https://www.tobias-erichsen.de/software/loopmidi.html">loopMIDI</a>，新增一個埠。',
      'Ableton Live：設定 → Link, Tempo &amp; MIDI → 把 IAC 或 loopMIDI 輸入的 Track 和 Remote 打開。TouchDesigner：在那個裝置上放一個 MIDI In CHOP。Resolume：Preferences → MIDI。',
    ],
    browsers: 'Chrome 和 Edge 有 Web MIDI，Firefox 會先問你是否允許這個網站。Safari 和 iPad 沒有：控制器照樣能彈、每個事件照樣送出，MIDI 輸出會顯示無法使用。',
    loop: '不會繞成迴圈。引擎本來就不聽 IAC 輸入，跟輸出同名的輸入（loopMIDI 自己的回音）也會靜音。實體控制器的動作不會再轉送一次，因為你的軟體本來就收得到那台。',
    protocolTitle: 'iframe 訊息',
    protocolText: 'iframe 會把每個事件傳給上層網頁，也接受幾個指令。加上 <code>&amp;frame=名稱</code> 可以分辨多個 iframe，加上 <code>&amp;origin=https://你的網站</code> 就只和你的網頁溝通。',
    apiTitle: '元素一覽',
    apiCols: { name: '名稱', kind: '種類', what: '做什麼' },
    api: [
      { name: 'profile', kind: '屬性', what: '哪一台：id、短名稱，或一個設定檔 JSON 的網址' },
      { name: 'layout', kind: '屬性', what: 'auto、face（照實物的樣子）或 stack（為直式畫面重新排）' },
      { name: 'hardware', kind: '屬性', what: '跟著實體裝置動：on、ask（顯示按鈕）或埠名稱' },
      { name: 'midi-out', kind: '屬性', what: '把彈的內容送到輸出埠：埠名稱、/正規表示式/，或 ask' },
      { name: 'channel', kind: '屬性', what: '1–16：把每個控制項移到你機器設定的頻道' },
      { name: 'picker · readout · learn · follow', kind: '屬性', what: '裝置選單、最後一則訊息、學習按鈕、接上哪台就切到哪台' },
      { name: 'control', kind: '事件', what: '任何控制項動了：id、type、value、raw、signal、message、bytes、source' },
      { name: 'noteon · noteoff', kind: '事件', what: '打擊墊、琴鍵和送音符的按鈕，附音高和力度' },
      { name: 'connect · disconnect · status', kind: '事件', what: '硬體埠接上或拔掉，以及硬體與 MIDI 輸出的狀態' },
      { name: 'set(id, value) · get(id) · values() · reset()', kind: '方法', what: '用程式轉一個控制項、讀一個、全部讀、全部歸零' },
      { name: 'ingest(bytes) · send(bytes)', kind: '方法', what: '從任何地方餵 MIDI 進來（面板會跟著動）· 把位元組送到輸出埠' },
      { name: 'on(name, fn)', kind: '方法', what: '訂閱事件，回傳取消訂閱的函式' },
    ],
    readme: '全部的細節，包括每個事件的每個欄位：套件的 README',
  },

  model: {
    eyebrow: '05 · 自己建一台',
    title: '加入你的控制器',
    lede: '一台控制器就是一個 JSON 檔。手冊裡有 MIDI 實作表，就照著抄，數字會完全準確。手冊沒寫的，就在檔案裡註明是怎麼查到的。',
    steps: [
      { head: '從最接近的檔案開始', text: '複製一台長得像你那台的裝置，或一個通用版面。面板是用面板單位排在格線上的區塊，所以螢幕上的版本看起來就像桌上那台。' },
      { head: '寫下每個控制項送什麼', text: '類型、訊息（<code>cc</code>、<code>note</code>、<code>pitchbend</code>）、頻道、編號。無段旋鈕寫明相對值怎麼編碼，按鈕寫是按住還是切換，有 LED 就寫哪個訊息會點亮它。' },
      { head: '每個數字都要有出處', text: '每份出處都有標題、連結，以及它證實了什麼。沒人確認過的數字，標上 <code>"verified": false</code> 並寫一句說明。' },
      { head: '驗證', text: '<code>validateProfile()</code> 會用文字列出每一個問題，沒有問題就回傳空陣列。測試會對每個內建設定檔跑一次。' },
      { head: '送出前先試', text: '<code>&lt;oav-controller profile="./my-pads.json"&gt;</code> 可以從網址載入設定檔，先在你自己的網頁上彈彈看。' },
      { head: '開一個 pull request', text: '把檔案放進 <code>packages/midi/profiles/</code>，在 <code>profiles/index.js</code> 加上它。告訴我們你在哪台機器、哪個韌體上確認過。' },
    ],
    typesTitle: '控制項類型',
    typesCols: { type: '類型', sends: '送出', signal: '訊號數值' },
    types: [
      { type: 'knob · fader', sends: 'CC，絕對值 0–127', signal: '0..1' },
      { type: 'encoder', sends: 'CC，相對值（offset64、offset16、twos、signbit）', signal: '位置 0..1，另有 /delta 步數' },
      { type: 'pad', sends: '帶力度的音符（或 CC），可能有觸後', signal: '按住時是力度，放開是 0，另有 /hit' },
      { type: 'button', sends: '音符或 CC，按住或切換', signal: '0 或 1' },
      { type: 'keys', sends: '一段音域', signal: '/on、/off 脈衝，按住時 n&lt;音高&gt;' },
      { type: 'wheel · strip', sends: 'CC 或彎音，可能會回彈', signal: '0..1，雙極時 −1..1' },
    ],
    schemaTitle: '設定檔長這樣',
    validateTitle: '檢查它',
    learnTitle: '沒有說明書？用學習模式',
    learnText: '選一個通用版面，按「學習」，照順序動一次你的控制項，版面會自己填上你那台送出的訊息。<code>exportMapping()</code> 把結果存成 JSON，就是一份設定檔的起點。',
    links: { repo: '原始碼庫', readme: 'packages/midi/README.md', folder: '所有設定檔', issue: '許願一台控制器' },
  },
};
