// Homepage strings, English (the default page, served at /).
// Shape must match zh.mjs key for key — tools/build-home.mjs refuses to build otherwise.
// Strings may contain inline HTML (authored, trusted). Code, signal names and URLs live in page.mjs.

export default {
  lang: 'en',
  htmlLang: 'en',
  hreflang: 'en',
  ogLocale: 'en_US',
  ldLanguage: 'en',

  meta: {
    title: 'open-audiovisual · a web-native framework for audiovisual performance',
    description: 'MIDI, microphones, chords, hands and phones become named signals, a mapping turns them into parameters, and your world draws and sounds them. A JavaScript framework for live audiovisual shows. Zero build, zero dependencies, MIT.',
    ogDescription: 'Hydra gives you improvisation. cables gives you a platform. Tone gives you sound. open-audiovisual gives you a show.',
    ld: 'A web-native, zero-build, zero-dependency JavaScript framework for audiovisual performance: inputs (MIDI, audio, chords, body pose, phones) publish named signals, a mapping layer routes them to parameters, and algorithmic worlds render and sound them, with a timeline, a director\'s console and a backstage monitor.',
  },

  ui: {
    skip: 'Skip to content',
    navLabel: 'Sections',
    nav: { play: 'Play', how: 'How it works', works: 'Works', start: 'Start', controllers: 'Controllers', docs: 'Docs', agents: 'For agents' },
    langLabel: 'Language',
    copy: 'Copy',
    copied: 'Copied',
    open: 'Open',
    source: 'Source',
    home: 'open-audiovisual home',
  },

  hero: {
    eyebrow: 'v0.1 · MIT · zero build · zero dependencies',
    sub: 'A web-native framework for audiovisual performance.',
    lede: 'Keys, knobs, voices, hands and phones become named <em>signals</em>. A <em>mapping</em> turns signals into <em>parameters</em>. Your <em>world</em> reads the parameters and turns them into image and sound, in a browser tab, on a projector, on stage.',
    doorsLabel: 'Where to start',
    doors: [
      { who: 'I perform', what: 'See what it makes and play the nine works', href: '#works' },
      { who: 'I write code', what: 'Run it in a minute, then write a world', href: '#start' },
      { who: 'I am an AI agent', what: 'Read /llms.txt, then AGENTS.md', href: 'llms.txt' },
    ],
  },

  inst: {
    eyebrow: '01 · Play',
    title: 'This instrument is the framework running',
    stageLabel: 'L3 world · harmonograph',
    canvasLabel: 'Harmonograph: every note you play swings a pendulum at its pitch. A consonant chord draws a clean figure, a cluster draws a tangle.',
    noscript: 'This instrument is the framework running live. Turn on JavaScript to play it.',
    statusSim: 'The simulated performer is playing. Your turn: tap the keys, or press A to L.',
    statusYou: 'You are playing. Drag on the stage to bend hue and twist.',
    statusIdle: 'Tap the keys or the stage, or press A to L, to play.',
    controlsLabel: 'Instrument switches',
    btnAuto: 'Autoplay',
    btnSound: 'Sound',
    btnMidi: 'MIDI',
    btnMic: 'Mic',
    keysHint: 'A–L play · Z/X octave · drag the stage',
    keysLabel: 'Piano keys',
    midiNone: 'No MIDI device found. Plug one in and press MIDI again.',
    midiOn: 'MIDI on: {n} device(s). Mod wheel (CC 1) also drives twist.',
    micOn: 'Mic on. Loudness now drives energy.',
    micDenied: 'The microphone is blocked in this browser.',
    soundLoading: 'Loading the synth…',
    soundOn: 'Sound on (Tone.js).',
    consonance: 'consonance',
    voices: 'voices',
    bayTitle: 'Patch bay',
    bayLive: 'live',
    srcHead: 'Signals',
    srcNote: 'what is happening',
    dstHead: 'Params',
    dstNote: 'what the world listens to',
    eventTarget: 'world (event)',
    waiting: 'dimmed: waiting for a device',
    legend: 'Each wire is a route in the mapper, drawn from its real data. The world reads only the right-hand column, so you can rewire the left without touching it.',
    caption: 'The world on this stage is a harmonograph, the pendulum drawing machine that turned musical intervals into figures. Each note you play swings one pendulum at its pitch. The chord analyzer reads what you hold and sends its consonance through one route, <code>chord/consonance → order</code>: a triad draws a clean figure, a cluster draws a tangle.',
    sourceLink: 'Read the source of this instrument',
  },

  how: {
    eyebrow: '02 · How it works',
    title: 'Four layers, kept apart',
    lede: 'A performance has four parts: something happens, it means something, a world reacts, and the result leaves the browser. open-audiovisual keeps the four apart, so you can swap any one of them and keep the rest.',
    layers: [
      { name: 'Input', quote: 'what is happening', text: 'A MIDI key, a microphone, a chord, a hand in front of the camera, a phone tilted in the air. Each one becomes a <em>signal</em>: a name and a number, usually between 0 and 1.' },
      { name: 'Mapping', quote: 'what it means', text: 'Routes connect signals to <em>params</em>, each with a curve, a range and smoothing. One knob can drive three params. Press learn, move anything, and it is wired.' },
      { name: 'World', quote: 'how it behaves', text: 'Your piece. It reads params, never inputs, and draws with whatever you like: canvas, p5, three.js, a WebToe node patch.' },
      { name: 'Output', quote: 'how it leaves', text: 'The screen, and sound: a synth in the page, MIDI out to hardware and DAWs, OSC to Spat, Reaper, TouchDesigner or lights.' },
    ],
    specimenLabel: 'from the instrument above',
    spinesTitle: 'Around the four layers',
    spines: [
      { name: 'Timeline', text: 'The score: param automation, scenes and cues. When a hand grabs a control, the score yields.' },
      { name: 'Console', text: 'The director\'s desk: transport, sliders, learn, meters, and a performance mode on T.' },
      { name: 'Monitor', text: 'Backstage on any phone or laptop on the network: clock, scene, every signal, FPS, and an alarm when the stage feed drops.' },
      { name: 'Phones', text: 'Phones and iPads as controllers: tilt and knock sensors, a keyboard, and a control surface grown from the world\'s params.' },
    ],
    rulesTitle: 'Two rules',
    rules: [
      { head: 'Signals are the only currency of input.', text: 'A knob, a raised hand and a chord\'s consonance are equal citizens with names. That equality is what lets you mix them.' },
      { head: 'Worlds never know who is performing them.', text: 'A world reads params. The same world can be played by a pianist, a dancer, or an automation curve.' },
    ],
    glossaryTitle: 'Words used on this page',
    glossary: [
      { term: 'Signal', def: 'A named value that says what is happening, such as <code>midi/cc/74</code> or <code>audio/rms</code>. Usually 0 to 1. Pulse signals carry events, like a note being struck.' },
      { term: 'Param', def: 'A value the world listens to, such as <code>hue</code> or <code>bloom</code>. The world declares it. The timeline, a slider or a route sets it.' },
      { term: 'Mapping, route', def: 'A wire from a signal to a param, with a curve, a range and smoothing. Routes are data, saved as JSON, so a wiring can travel between venues.' },
      { term: 'World', def: 'The piece itself: an object with <code>params</code>, <code>init</code>, <code>update</code>, <code>render</code> and <code>dispose</code>. The only part you have to write.' },
      { term: 'Timeline', def: 'Automation and scenes over time. The baseline that hands and knobs override.' },
      { term: 'Show', def: 'A world plus one <code>createShow()</code> call, which assembles inputs, mapping, timeline, console, sound and backstage.' },
    ],
  },

  works: {
    eyebrow: '03 · Works',
    title: 'Nine works you can open now',
    lede: 'Every example runs without hardware. An on-screen piano, QWERTY keys, a simulated performer or a drum machine stands in for instruments. In any example: Space plays the timeline, T is performance mode, F is fullscreen.',
    playsWith: 'Plays with',
    items: [
      { title: 'Hello particles', inputs: 'on-screen piano · QWERTY · simulated performer', text: 'The smallest complete app. Read its <code>main.js</code> from top to bottom and you know the framework.', alt: 'Bursts of thin green and red particle trails falling on black.' },
      { title: 'Chord garden', inputs: 'on-screen piano · QWERTY · simulated performer', text: 'A triad makes the garden bloom, a cluster makes it decay. The world listens to chord signals, never to keys. From The Last Input.', alt: 'Rows of thin green and blue stems with bright tips growing from the bottom edge.' },
      { title: 'Hand instrument', inputs: 'camera (hands) · on-screen piano · drum machine', text: 'Fingers as an instrument: one pinch sets tightness, another grows arms, both fists bloom. Four pattern families: mandala, lissajous, spirograph, web.', alt: 'A blue and white mandala of fine layered lines.' },
      { title: 'WebToe stage', inputs: 'on-screen piano · simulated performer', text: 'The world is a WebToe node patch, TouchDesigner-style, performed through <code>ext()</code> bindings. WebToe is the engine, open-audiovisual is the show.', alt: 'A node editor with noise, level and output nodes beside a grey cloud texture.' },
      { title: 'Prebiotic flake', inputs: 'on-screen piano · simulated performer · sound', text: 'A 2023 MIDI daily sketch replayed through the framework. The drawing code is the original. The flakes now have a voice through Tone.js.', alt: 'A glowing yellow ring of jagged petals with small circles inside.' },
      { title: 'Cylinder earth', inputs: 'microphone · drum machine', text: 'A 2020 voice-controlled WebGL sketch. Lows pump the towers, highs shimmer the spin, a kick turns the palette.', alt: 'A sphere packed with colourful cylinders seen end-on, like umbrellas.' },
      { title: 'Firework festival', inputs: 'camera (hands) · on-screen piano', text: 'A 2021 sketch. Close a finger pinch and a firework launches from that hand. The particle system is the 2021 code.', alt: 'Cyan and violet fireworks bursting over drooping coloured trails.' },
      { title: 'Remote surface', inputs: 'phone or iPad · on-screen piano', text: 'The phone is the instrument panel. The world only declares params, and the control surface on the phone grows from them. Needs <code>node serve.js</code> on your network.', alt: 'Blue and yellow streaks exploding outward from the lower centre.' },
      { title: 'MIDI controllers', inputs: 'MIDI controller, or the on-screen one', text: 'On-screen MiniLab 3, LPD8, Launchpad and nanoKONTROL2. Plug the real one in and the on-screen one moves with your hands.', alt: 'A spiral of pink and blue dots above an on-screen MIDI keyboard controller.' },
    ],
    credits: [
      'Che-Yu Wu, <cite>230616 Prebiotic Flake</cite>, 2023',
      'Che-Yu Wu, <cite>200412 3D Cylinder Earth</cite>, 2020',
      'Che-Yu Wu, <cite>210807 Firework 花火大會</cite>, 2021',
    ],
    note: 'Works 05 to 07 are artworks by Che-Yu Wu (2020 to 2023), used here as demos. The framework is MIT. The artworks remain © the artist, all rights reserved.',
  },

  start: {
    eyebrow: '04 · Start',
    title: 'Run it in a minute',
    lede: 'No install, no build, no dependencies. Clone, run one file, open the browser. Use Chrome or Edge for Web MIDI and the camera.',
    after: 'Then open <code>http://localhost:8080/examples/01-hello-particles/</code> and read its <code>main.js</code>.',
    companions: 'Optional, each in its own terminal: the backstage monitor and the OSC bridge to UDP.',
    worldTitle: 'A world is the only part you write',
    worldText: 'Declare what the piece can be performed with (params), react to events, draw. Hand it to <code>createShow()</code> and the rest arrives with it: piano, mapping, timeline, console, sound, backstage. Put it next to an <code>index.html</code> with the import map, as in example 01.',
    worldLink: 'Writing a world',
    packagesTitle: 'Twenty packages, by layer',
    packagesLede: 'Plain ES modules. Import what you need through an import map, or let <code>createShow()</code> assemble them.',
    groups: ['Input', 'Mapping', 'World', 'Output', 'Spines', 'Phones and tablets', 'Glue and agents'],
    packages: {
      midi: 'Web MIDI in and out, many devices, on-screen controller profiles',
      audio: 'Microphone analysis: loudness, bands, brightness, onsets, drum hits',
      chord: 'Chord detection for performance: consonance, triads, clusters',
      pose: 'Body and 21-point hand tracking from the camera, on the device',
      keys: 'On-screen piano, QWERTY playing and a simulated performer',
      drums: 'Synth kit and step sequencer that publish analyzer-shaped signals',
      mapping: 'Signal to param routes: curves, smoothing, many-to-many, learn',
      stage: 'The world shell: lifecycle and params, no renderer opinion',
      'world-webtoe': 'Perform a WebToe node patch as a world',
      sound: 'Synthesis in the page behind a small engine contract, Tone.js first',
      osc: 'OSC out of the browser through a small Node bridge to UDP',
      timeline: 'Param automation, scenes and cues: the score of the show',
      console: 'The director\'s desk and performance mode',
      monitor: 'Backstage view for any device on the network',
      relay: 'Zero-dependency room relay for phones and iPads',
      surface: 'TouchOSC-style widgets and autoSurface(params)',
      remote: 'The phone and iPad app: sensors, keyboard, control surface',
      core: 'Signals, Params and Loop: what every layer speaks',
      show: 'createShow(): one call assembles the whole shell',
      mcp: 'MCP server for coding agents: list, read, scaffold, check',
    },
    docsTitle: 'Documentation',
    docs: {
      architecture: 'The layer contracts, in detail',
      world: 'The world interface and the rule people break',
      signals: 'Every signal the built-in inputs publish',
      show: 'Timeline, scenes, performance mode, monitor, OSC',
      roadmap: 'What a real show asked for next',
      agents: 'Conventions for AI coding agents',
    },
    docsNote: '',
    docNames: { architecture: 'Architecture', world: 'Writing a world', signals: 'Signals reference', show: 'Show control', roadmap: 'Roadmap', agents: 'AGENTS.md' },
  },

  agents: {
    eyebrow: '05 · For AI agents',
    title: 'For AI agents',
    lede: 'Worlds are code, and coding agents are good at code. A person describes a performance in words, the agent writes the world, and the framework runs the show.',
    promptTitle: 'Paste this into Claude Code, Cursor or any coding agent',
    prompt: [
      'Clone https://github.com/frank890417/open-audiovisual and read AGENTS.md first.',
      'Run `node serve.js` and open http://localhost:8080/examples/01-hello-particles/ to see the smallest complete show.',
      'Create examples/10-<name>/ by copying 01-hello-particles (or call the openav MCP tool scaffold_world), then write a World in its main.js for this piece:',
      '',
      '  <describe the performance, e.g. "a jellyfish world that blooms on consonant chords">',
      '',
      'Rules from AGENTS.md: continuous control goes through params, and the mapper routes signals to them. Never edit packages/* to make one example look right.',
      'Done means: npm test passes, and the new example loads with zero console errors.',
    ],
    mcpTitle: 'Connect the MCP server',
    mcpText: 'The repo ships a zero-dependency MCP server over stdio. Claude Code picks it up from <code>.mcp.json</code> when you open the repo. For other clients, point at the file:',
    toolsTitle: 'Tools',
    tools: {
      list_examples: 'which works exist, with a one-line summary each',
      read_doc: 'architecture, writing-a-world, signals, show-control, agents',
      scaffold_world: 'copy a donor example into a new numbered example',
      run_checks: 'run the test suite, the same gate CI uses',
    },
    filesTitle: 'Machine-readable',
    files: {
      llms: 'what this is, the concepts, every doc and example, in llmstxt.org format',
      llmsFull: 'README, AGENTS.md and the docs in one file',
      agentsMd: 'the layer contracts and the two rules an agent must not break',
      skill: 'a Claude Code skill that scaffolds a world from a description',
      ld: 'this page carries SoftwareSourceCode JSON-LD',
      alt: 'this page in Traditional Chinese',
    },
  },

  lineage: {
    eyebrow: '06 · Lineage',
    title: 'Extracted from a show',
    p1: 'The core of open-audiovisual comes from <a href="https://cheyuwu.com/exhibition/the-last-input"><cite>The Last Input</cite></a> (Che-Yu Wu, 2026), a 49.4-channel spatial sound performance at the IRCAM residency × C-LAB in Taipei, where a pianist feeds a living digital world. Its timeline, chord semantics, many-to-many MIDI learn and OSC batching drove a real 14-scene show before they were generalized here. The rule since then: the framework only grows features a real show asked for.',
    p2: 'The mapping layer descends from <a href="http://libmapper.github.io/">libmapper</a>\'s research on signal namespaces. The sister project <a href="https://github.com/frank890417/WebToe">WebToe</a> is a node-based dataflow engine that imports TouchDesigner projects. WebToe is the engine, open-audiovisual is the show.',
    quote: 'Hydra gives you improvisation. cables gives you a platform. Tone gives you sound. <strong>open-audiovisual gives you a show.</strong>',
    quoteCite: 'README',
    nextTitle: 'Next, from the roadmap',
    next: [
      'Record the full signal stream of a performance and replay it into any world',
      'npm packages, and a docs site built on the framework itself',
      'A WebGPU world adapter for particle and agent worlds',
      'An NDI gateway so browser output enters professional video pipelines',
      'Several machines sharing one signal space over WebRTC',
      'Agents that subscribe to signals and play alongside people',
    ],
    roadmapLink: 'Full roadmap',
  },

  footer: {
    pages: 'Pages',
    homeLink: 'Home',
    license: 'MIT license. Made by <a href="https://cheyuwu.com">Che-Yu Wu 吳哲宇</a>.',
    artworks: 'Examples 05 to 07 integrate artworks © Che-Yu Wu, all rights reserved.',
    machine: 'For machines',
  },
};
