// 首頁字串，繁體中文（台灣），輸出到 /zh/。
// 結構必須和 en.mjs 一模一樣（每個 key、每個陣列長度），tools/build-home.mjs 會檢查。
// 字串可以含 inline HTML。程式碼、訊號名稱與網址放在 page.mjs，兩種語言共用。

export default {
  lang: 'zh',
  htmlLang: 'zh-Hant-TW',
  hreflang: 'zh-Hant',
  ogLocale: 'zh_TW',
  ldLanguage: 'zh-Hant-TW',

  meta: {
    title: 'open-audiovisual｜網頁原生的影音表演框架',
    description: 'MIDI、麥克風、和弦、手勢和手機，都變成有名字的訊號，經過映射接到參數，交給你的世界去畫、去發聲。一套給現場影音表演用的 JavaScript 框架。零建置、零相依、MIT 授權。',
    ogDescription: 'Hydra 給你即興，cables 給你平台，Tone 給你聲音。open-audiovisual 給你一場演出。',
    ld: '網頁原生、零建置、零相依的 JavaScript 影音表演框架：MIDI、音訊、和弦、肢體姿態與手機等輸入發出有名字的訊號，映射層把訊號接到參數，演算的世界依參數產生畫面與聲音，另有時間軸、導演控台與後台監看。',
  },

  ui: {
    skip: '跳到主要內容',
    navLabel: '頁面區塊',
    nav: { play: '彈奏', how: '運作方式', works: '作品', start: '開始', agents: '給 AI 代理' },
    langLabel: '語言',
    copy: '複製',
    copied: '已複製',
    open: '開啟',
    source: '原始碼',
    home: 'open-audiovisual 首頁',
  },

  hero: {
    eyebrow: 'v0.1 · MIT 授權 · 零建置 · 零相依',
    sub: '網頁原生的影音表演框架。',
    lede: '琴鍵、旋鈕、人聲、手勢、手機，都會變成有名字的<em>訊號</em>（signal）。<em>映射</em>（mapping）把訊號接到<em>參數</em>（param），你的<em>世界</em>（world）讀這些參數，變成畫面和聲音。在瀏覽器分頁、投影機、舞台上都一樣。',
    doorsLabel: '從哪裡開始',
    doors: [
      { who: '我做表演', what: '看看它做得出什麼，直接玩九件作品', href: '#works' },
      { who: '我寫程式', what: '一分鐘跑起來，再寫自己的世界', href: '#start' },
      { who: '我是 AI 代理', what: '先讀 /llms.txt，再讀 AGENTS.md', href: 'llms.txt' },
    ],
  },

  inst: {
    eyebrow: '01 · 彈奏',
    title: '這台樂器就是框架本身在跑',
    stageLabel: 'L3 世界 · 擺錘繪圖機',
    canvasLabel: '擺錘繪圖機：你彈的每個音，會依音高擺動一支擺錘。和諧的和弦畫出乾淨的圖形，音堆畫出糾纏的線。',
    noscript: '這台樂器是框架即時在跑的樣子，開啟 JavaScript 就能彈。',
    statusSim: '模擬演奏者正在彈。換你了：點琴鍵，或按電腦鍵盤 A 到 L。',
    statusYou: '現在是你在彈。在畫面上拖曳，可以改色相和扭轉。',
    statusIdle: '點琴鍵或畫面，或按電腦鍵盤 A 到 L，就能彈。',
    controlsLabel: '樂器開關',
    btnAuto: '自動演奏',
    btnSound: '聲音',
    btnMidi: 'MIDI',
    btnMic: '麥克風',
    keysHint: 'A 到 L 彈奏 · Z／X 換八度 · 拖曳畫面',
    keysLabel: '琴鍵',
    midiNone: '找不到 MIDI 裝置。接上之後，再按一次 MIDI。',
    midiOn: 'MIDI 已開啟，{n} 個裝置。調變輪（CC 1）也會帶動扭轉。',
    micOn: '麥克風已開啟，音量現在帶動能量。',
    micDenied: '這個瀏覽器擋下了麥克風。',
    soundLoading: '正在載入合成器…',
    soundOn: '聲音已開啟（Tone.js）。',
    consonance: '協和度',
    voices: '聲部',
    bayTitle: '跳線盤',
    bayLive: '即時',
    srcHead: '訊號',
    srcNote: '正在發生什麼',
    dstHead: '參數',
    dstNote: '世界在聽什麼',
    eventTarget: '世界（事件）',
    waiting: '變暗的線：等裝置接上',
    legend: '每一條線都是映射器裡的一條路由（route），照它真正的資料畫出來。世界只讀右邊那一欄，左邊怎麼重接，世界都不用改。',
    caption: '舞台上的世界是一台擺錘繪圖機（harmonograph），用擺錘把音程畫成圖形的老機器。你彈的每個音，會依音高擺動一支擺錘。和弦分析器讀你按住的音，把協和度經過一條路由 <code>chord/consonance → order</code> 送進世界：三和弦畫出乾淨的圖形，音堆畫出一團糾纏的線。',
    sourceLink: '看這台樂器的原始碼',
  },

  how: {
    eyebrow: '02 · 運作方式',
    title: '四層，各自分開',
    lede: '一場表演有四個部分：發生了什麼、它代表什麼、世界怎麼反應、結果怎麼離開瀏覽器。open-audiovisual 讓這四層各自分開，換掉其中一層，其他三層照常運作。',
    layers: [
      { name: '輸入', quote: '正在發生什麼', text: 'MIDI 琴鍵、麥克風、一個和弦、鏡頭前的一隻手、在空中傾斜的手機。每一種都會變成<em>訊號</em>：一個名字加一個數值，通常在 0 到 1 之間。' },
      { name: '映射', quote: '它代表什麼', text: '路由把訊號接到<em>參數</em>，每一條都能設曲線、範圍和平滑。一顆旋鈕可以同時推三個參數。按下 learn，隨便動一樣東西，線就接好了。' },
      { name: '世界', quote: '系統怎麼表現', text: '你的作品。它只讀參數，不碰輸入，用什麼畫都可以：canvas、p5、three.js、WebToe 節點網路。' },
      { name: '輸出', quote: '怎麼離開瀏覽器', text: '螢幕，還有聲音：頁面裡的合成器、送到硬體和 DAW 的 MIDI、送到 Spat、Reaper、TouchDesigner 或燈光的 OSC。' },
    ],
    specimenLabel: '數值來自上面那台樂器',
    spinesTitle: '四層之外',
    spines: [
      { name: '時間軸 Timeline', text: '整場演出的樂譜：參數自動化、場景與 cue。手一抓住控制，樂譜就讓位。' },
      { name: '控台 Console', text: '導演桌：播放控制、推桿、learn、儀表，按 T 進入演出模式。' },
      { name: '後台監看 Monitor', text: '同一個網路裡的手機或筆電都能當後台：時鐘、場景、每個訊號、FPS，舞台畫面斷線時會警示。' },
      { name: '手機 Phones', text: '手機和 iPad 當控制器：傾斜和敲擊感測、琴鍵，還有依世界的參數自動長出來的控制面板。' },
    ],
    rulesTitle: '兩條規則',
    rules: [
      { head: '訊號是輸入唯一的通用貨幣。', text: '一顆旋鈕、一隻舉起的手、一個和弦的協和度，在框架裡地位相同，各有名字。所以它們可以混在一起用。' },
      { head: '世界永遠不知道誰在演奏它。', text: '世界只讀參數。同一個世界，可以由鋼琴家、舞者，或一條自動化曲線來演奏。' },
    ],
    glossaryTitle: '這一頁用到的詞',
    glossary: [
      { term: '訊號 Signal', def: '一個有名字的數值，說明正在發生什麼，例如 <code>midi/cc/74</code>、<code>audio/rms</code>。通常在 0 到 1 之間。脈衝訊號（pulse）帶的是事件，例如一個音被按下。' },
      { term: '參數 Param', def: '世界在聽的數值，例如 <code>hue</code>、<code>bloom</code>。由世界宣告，由時間軸、推桿或路由來設定。' },
      { term: '映射、路由 Mapping, route', def: '一條從訊號接到參數的線，可以設曲線、範圍和平滑。路由本身就是資料，存成 JSON，接線方式可以帶到下一個場地。' },
      { term: '世界 World', def: '作品本身：一個帶有 <code>params</code>、<code>init</code>、<code>update</code>、<code>render</code>、<code>dispose</code> 的物件。整套框架裡，唯一一定要自己寫的部分。' },
      { term: '時間軸 Timeline', def: '隨時間變化的自動化與場景。手和旋鈕一動，就會蓋過它。' },
      { term: '演出 Show', def: '一個世界，加上一次 <code>createShow()</code> 呼叫，輸入、映射、時間軸、控台、聲音和後台就一起組好。' },
    ],
  },

  works: {
    eyebrow: '03 · 作品',
    title: '九件作品，現在就能打開',
    lede: '每個範例都不需要硬體。螢幕鋼琴、電腦鍵盤、模擬演奏者或鼓機，可以先代替樂器。進到任何一個範例：空白鍵播放時間軸，T 是演出模式，F 是全螢幕。',
    playsWith: '演奏方式',
    items: [
      { title: '哈囉粒子', inputs: '螢幕鋼琴 · 電腦鍵盤 · 模擬演奏者', text: '最小的完整範例。把 <code>main.js</code> 從頭讀到尾，整套框架就懂了。', alt: '黑底上，粒子拖著細細的綠色與紅色尾巴落下。' },
      { title: '和弦花園', inputs: '螢幕鋼琴 · 電腦鍵盤 · 模擬演奏者', text: '彈三和弦，花園開花，彈音堆，花園枯萎。世界聽的是和弦訊號，從來不看琴鍵。來自《The Last Input》。', alt: '細細的綠色與藍色莖從底部長起，頂端發亮。' },
      { title: '手的樂器', inputs: '鏡頭（手）· 螢幕鋼琴 · 鼓機', text: '手指就是樂器：一組捏合控制鬆緊，另一組長出手臂，兩手握拳就綻放。四種圖案輪流切換：曼陀羅、利薩如、萬花尺、蛛網。', alt: '藍白色細線層層疊成的曼陀羅。' },
      { title: 'WebToe 舞台', inputs: '螢幕鋼琴 · 模擬演奏者', text: '這個世界是一張 WebToe 節點網路，操作方式接近 TouchDesigner，透過 <code>ext()</code> 綁定來演奏。WebToe 是引擎，open-audiovisual 是演出。', alt: '節點編輯器裡有 noise、level、out 三個節點，旁邊是灰色雲霧材質。' },
      { title: 'Prebiotic Flake', inputs: '螢幕鋼琴 · 模擬演奏者 · 聲音', text: '2023 年的一件 MIDI 每日創作，搬進框架重新演奏。繪圖程式碼保持原樣，雪花現在透過 Tone.js 發出聲音。', alt: '發光的黃色鋸齒花瓣圍成一圈，中間有小圓圈。' },
      { title: 'Cylinder Earth', inputs: '麥克風 · 鼓機', text: '2020 年用聲音控制的 WebGL 作品。低頻推動柱體，高頻讓旋轉閃爍，大鼓一下就換一組配色。', alt: '一顆球體擠滿彩色圓柱，從端面看去像一把把傘。' },
      { title: '花火大會', inputs: '鏡頭（手）· 螢幕鋼琴', text: '2021 年的作品。手指一捏合，煙火就從那隻手的位置升空。粒子系統是 2021 年的原始程式碼。', alt: '青色和紫色的煙火，在垂落的彩色尾跡上炸開。' },
      { title: '遠端控制面板', inputs: '手機或 iPad · 螢幕鋼琴', text: '手機就是樂器面板。世界只宣告參數，手機上的控制面板依參數自動長出來。需要在你的網路裡跑 <code>node serve.js</code>。', alt: '藍色和黃色的光束，從畫面下方中央向外爆開。' },
      { title: 'MIDI 控制器', inputs: 'MIDI 控制器，或螢幕上那一台', text: '螢幕上有 MiniLab 3、LPD8、Launchpad、nanoKONTROL2。接上實體控制器，螢幕上那台會跟著你的手一起動。', alt: '粉紅與藍色圓點排成螺旋，下方是螢幕上的 MIDI 鍵盤控制器。' },
    ],
    credits: [
      '吳哲宇，<cite>230616 Prebiotic Flake</cite>，2023',
      '吳哲宇，<cite>200412 3D Cylinder Earth</cite>，2020',
      '吳哲宇，<cite>210807 Firework 花火大會</cite>，2021',
    ],
    note: '05 到 07 是吳哲宇 2020 到 2023 年的作品，在這裡當作示範。框架採 MIT 授權，作品的著作權仍屬藝術家，保留一切權利。',
  },

  start: {
    eyebrow: '04 · 開始',
    title: '一分鐘跑起來',
    lede: '不用安裝、不用建置、沒有相依套件。clone 下來，跑一個檔案，打開瀏覽器。要用 Web MIDI 和鏡頭，請用 Chrome 或 Edge。',
    after: '接著打開 <code>http://localhost:8080/examples/01-hello-particles/</code>，讀它的 <code>main.js</code>。',
    companions: '需要的話，各開一個終端機：後台監看伺服器，以及把 OSC 送到 UDP 的橋接。',
    worldTitle: '你只需要寫一個世界',
    worldText: '宣告作品能被什麼演奏（參數），對事件做反應，然後畫出來。交給 <code>createShow()</code>，其他部分一起到位：鋼琴、映射、時間軸、控台、聲音、後台。旁邊放一個帶 import map 的 <code>index.html</code>，照範例 01 的寫法。',
    worldLink: '怎麼寫一個世界',
    packagesTitle: '二十個套件，依層分類',
    packagesLede: '全部是原生 ES module。用 import map 引入需要的套件，或交給 <code>createShow()</code> 組裝。',
    groups: ['輸入', '映射', '世界', '輸出', '時間軸、控台、監看', '手機與平板', '核心與代理'],
    packages: {
      midi: 'Web MIDI 輸入與輸出，支援多台裝置與螢幕上的控制器',
      audio: '麥克風分析：音量、頻段、亮度、起音、鼓點',
      chord: '為演出設計的和弦偵測：協和度、三和弦、音堆',
      pose: '用鏡頭追蹤身體與手的 21 個點，全部在本機運算',
      keys: '螢幕鋼琴、電腦鍵盤演奏，以及模擬演奏者',
      drums: '合成鼓組與步進音序器，發出和音訊分析同樣形狀的訊號',
      mapping: '訊號到參數的路由：曲線、平滑、多對多、learn',
      stage: '世界的外殼：管生命週期和參數，不限定繪圖方式',
      'world-webtoe': '把 WebToe 節點網路當成世界來演奏',
      sound: '頁面裡的合成器，背後是精簡的引擎介面，先支援 Tone.js',
      osc: '透過一支小小的 Node 橋接，把 OSC 從瀏覽器送到 UDP',
      timeline: '參數自動化、場景與 cue：整場演出的樂譜',
      console: '導演控台與演出模式',
      monitor: '網路裡任何裝置都能看的後台畫面',
      relay: '零相依的房間中繼，讓手機和 iPad 連進來',
      surface: '類似 TouchOSC 的控制元件，以及 autoSurface(params)',
      remote: '手機與 iPad 端的 app：感測器、琴鍵、控制面板',
      core: 'Signals、Params、Loop：每一層共用的語言',
      show: 'createShow()：一次呼叫組好整個外殼',
      mcp: '給程式代理用的 MCP 伺服器：列出、閱讀、建立、檢查',
    },
    docsTitle: '文件',
    docs: {
      architecture: '每一層的介面約定，完整說明',
      world: '世界的介面，以及最常被打破的那條規則',
      signals: '內建輸入會發出的所有訊號',
      show: '時間軸、場景、演出模式、後台監看、OSC',
      roadmap: '真實演出接下來要求的功能',
      agents: '給 AI 程式代理的約定',
    },
    docsNote: '文件目前只有英文版。',
    docNames: { architecture: '架構', world: '寫一個世界', signals: '訊號一覽', show: '演出控制', roadmap: '路線圖', agents: 'AGENTS.md' },
  },

  agents: {
    eyebrow: '05 · 給 AI 代理',
    title: '給 AI 代理',
    lede: '世界就是程式碼，程式代理（coding agent）很會寫程式。人用文字描述一場表演，代理寫出世界，框架把演出跑起來。',
    promptTitle: '把這段貼給 Claude Code、Cursor 或任何程式代理',
    prompt: [
      'Clone https://github.com/frank890417/open-audiovisual，先讀 AGENTS.md。',
      '執行 `node serve.js`，打開 http://localhost:8080/examples/01-hello-particles/，看最小的完整演出長什麼樣子。',
      '把 01-hello-particles 複製成 examples/10-<名稱>/（或呼叫 openav MCP 的 scaffold_world 工具），在它的 main.js 為這件作品寫一個 World：',
      '',
      '  <描述這場表演，例如「一個遇到和諧和弦就綻放的水母世界」>',
      '',
      'AGENTS.md 的規則：連續控制一律走參數，由 mapper 把訊號接過去。不要為了讓某個範例好看去改 packages/*。',
      '完成的條件：npm test 通過，新範例載入時主控台零錯誤。',
    ],
    mcpTitle: '接上 MCP 伺服器',
    mcpText: 'repo 內附一個零相依、走 stdio 的 MCP 伺服器。在 repo 裡打開 Claude Code，會自動從 <code>.mcp.json</code> 讀到它。其他客戶端，把路徑指到這個檔案：',
    toolsTitle: '工具',
    tools: {
      list_examples: '有哪些作品，每件附一行摘要',
      read_doc: '架構、寫一個世界、訊號、演出控制、代理約定',
      scaffold_world: '拿一個範例當底，建立新的編號範例',
      run_checks: '跑測試，和 CI 是同一道關卡',
    },
    filesTitle: '給機器讀的',
    files: {
      llms: '這是什麼、核心概念、所有文件與範例，llmstxt.org 格式',
      llmsFull: 'README、AGENTS.md 和所有文件合成一個檔',
      agentsMd: '每一層的介面約定，以及代理不能打破的兩條規則',
      skill: 'Claude Code 技能：從一段描述建立一個世界',
      ld: '這一頁帶有 SoftwareSourceCode 的 JSON-LD',
      alt: '這一頁的英文版',
    },
  },

  lineage: {
    eyebrow: '06 · 來歷',
    title: '從一場演出裡抽出來',
    p1: 'open-audiovisual 的核心來自<a href="https://cheyuwu.com/zh/exhibition/the-last-input">《The Last Input 終局之前》</a>（吳哲宇，2026），IRCAM 聲鬥陣 × C-LAB 在台北的 49.4 聲道空間聲響演出，演奏者用鋼琴餵養一個活著的數位世界。時間軸、和弦語意、多對多的 MIDI learn、OSC 批次傳送，都先撐過一整場十四個場景的演出，才整理成這裡的通用框架。從那之後的規則：框架只長真實演出要求過的功能。',
    p2: '映射層的想法，承接 <a href="http://libmapper.github.io/">libmapper</a> 對訊號命名空間的研究。姊妹專案 <a href="https://github.com/frank890417/WebToe">WebToe</a> 是節點式的資料流引擎，可以匯入 TouchDesigner 專案。WebToe 負責引擎，open-audiovisual 負責演出。',
    quote: 'Hydra 給你即興，cables 給你平台，Tone 給你聲音。<strong>open-audiovisual 給你一場演出。</strong>',
    quoteCite: 'README',
    nextTitle: '接下來，摘自路線圖',
    next: [
      '錄下一場演出完整的訊號流，再播給任何一個世界',
      '發布 npm 套件，用這套框架本身做文件網站',
      'WebGPU 世界轉接，給粒子與群體代理類的世界',
      'NDI 閘道，讓瀏覽器的畫面進入專業影像流程',
      '多台電腦透過 WebRTC 共用同一個訊號空間',
      '訂閱訊號、和人一起演奏的 AI 演奏者',
    ],
    roadmapLink: '完整路線圖',
  },

  footer: {
    license: 'MIT 授權。<a href="https://cheyuwu.com/zh/">吳哲宇 Che-Yu Wu</a> 製作。',
    artworks: '範例 05 到 07 收錄吳哲宇的作品，著作權屬藝術家，保留一切權利。',
    machine: '給機器讀的',
  },
};
