#!/usr/bin/env node
// build-home — render the homepage in every language from ONE template.
//
//   node tools/build-home.mjs          # write index.html, zh/index.html, llms-full.txt, sitemap.xml
//   node tools/build-home.mjs --check  # exit 1 if the committed files are stale
//
// Why a generator in a zero-build framework: the site is two static pages
// (crawlers and AI agents must read both languages without running JS), and two
// hand-kept HTML files drift. The framework itself still needs no build step;
// this script only regenerates committed, static output. Inputs:
//   tools/home/page.mjs   structure, links, code, ids (shared)
//   tools/home/en.mjs     English strings  → /
//   tools/home/zh.mjs     Traditional Chinese strings → /zh/
// Run tools/stamp-version.mjs afterwards, as before every deploy (cache-busting);
// --check ignores ?v= stamps.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderPage, LOCALES } from './home/page.mjs';
import { PAGES, pageCtx } from './site/chrome.mjs';
import { CHAPTERS } from './docs/chapters.mjs';
import en from './home/en.mjs';
import zh from './home/zh.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const version = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;

/** Both string tables must have the same shape: same keys, same array lengths. */
export function shapeDiff(a, b, at = '') {
  const out = [];
  const kind = (v) => Array.isArray(v) ? 'array' : v === null ? 'null' : typeof v;
  if (kind(a) !== kind(b)) return [`${at || '(root)'}: ${kind(a)} vs ${kind(b)}`];
  if (kind(a) === 'array') {
    if (a.length !== b.length) out.push(`${at}: length ${a.length} vs ${b.length}`);
    for (let i = 0; i < Math.min(a.length, b.length); i++) out.push(...shapeDiff(a[i], b[i], `${at}[${i}]`));
  } else if (kind(a) === 'object') {
    for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
      if (!(k in a)) out.push(`${at}.${k}: missing in en`);
      else if (!(k in b)) out.push(`${at}.${k}: missing in zh`);
      else out.push(...shapeDiff(a[k], b[k], `${at}.${k}`));
    }
  }
  return out;
}

// README + AGENTS.md, then every docs chapter in the /docs/ handbook's order (tools/docs/chapters.mjs),
// so llms-full.txt and the handbook never disagree about what the documentation is.
const LLMS_SOURCES = ['README.md', 'AGENTS.md', ...CHAPTERS.map((c) => c.en)];

function llmsFull() {
  const head = `# open-audiovisual — full text for language models

> Every document of open-audiovisual in one file: README, AGENTS.md and every chapter of the handbook (docs/).
> Generated by tools/build-home.mjs from the repository; the short index is /llms.txt.
> Site: https://openaudiovisual.com/ (English) · https://openaudiovisual.com/zh/ (繁體中文)
> Handbook: https://openaudiovisual.com/docs/ · MIDI controller library: https://openaudiovisual.com/controllers/
> Repository: https://github.com/frank890417/open-audiovisual (MIT)
`;
  return head + LLMS_SOURCES.filter((f) => fs.existsSync(path.join(ROOT, f))).map(f =>
    `\n\n---\n\n<!-- source: ${f} -->\n\n` + fs.readFileSync(path.join(ROOT, f), 'utf8').trim()).join('') + '\n';
}

/** sitemap.xml: every page of the site (tools/site/chrome.mjs PAGES), both languages, hreflang-linked. */
export function sitemap() {
  const alt = (c) => [['en', c.url.en], ['zh-Hant', c.url.zh], ['x-default', c.url.en]]
    .map(([l, u]) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${u}"/>`).join('\n');
  const urls = Object.keys(PAGES).flatMap((p) => {
    const c = pageCtx(p, 'en');
    return [c.url.en, c.url.zh].map((u) => `  <url>\n    <loc>${u}</loc>\n${alt(c)}\n  </url>`);
  });
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`;
}

export function buildAll() {
  const diff = shapeDiff(en, zh);
  if (diff.length) throw new Error('string tables differ in shape:\n  ' + diff.join('\n  '));
  return {
    [LOCALES.en.path + 'index.html']: renderPage(en, { locale: 'en', other: 'zh', version }),
    [LOCALES.zh.path + 'index.html']: renderPage(zh, { locale: 'zh', other: 'en', version }),
    'llms-full.txt': llmsFull(),
    'sitemap.xml': sitemap(),
  };
}

const unstamp = (s) => s.replace(/\?v=[\w.-]+/g, '');

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = buildAll();
  const stale = [];
  for (const [rel, out] of Object.entries(files)) {
    const file = path.join(ROOT, rel);
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (check) { if (cur === null || unstamp(cur) !== unstamp(out)) stale.push(rel); continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, out);
    console.log('wrote', rel, `(${out.length} bytes)`);
  }
  if (check) {
    if (stale.length) { console.error('stale (run node tools/build-home.mjs):\n  ' + stale.join('\n  ')); process.exit(1); }
    console.log('✅ homepage up to date (en, zh, llms-full.txt, sitemap.xml)');
  }
}
